# Generated by Django 4.2.4 on 2023-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_actor_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
